services:
  llm-proxy:
    build:
      dockerfile: ./Dockerfile
      context: .
    expose:
      - "3000"
    environment:
      - LLM_PROXY_PROVIDER=AnyProvider
      - LLM_UPSTREAM=http://g4f:8080
    networks:
      - n8n_n8n_network 

networks:
  n8n_n8n_network:  
    external: true
    name: n8n_n8n_network  
      
